############################################################
## Hugo ClearStatus config
############################################################

# Complete page title
title: Android වැඩකාරයෝ systems status page

# Language config
languageCode: en

############################################################
## More default config. in /config/_default/config.yml
############################################################


############################################################
## Status default config. Valid for ALL languages.
############################################################

params:
  systems:
    - name: Website
      description: Android වැඩකාරයෝ website
      link: https://androidwedakarayo.com/

  # dateFormat Default: "January 2, 2006 at 3:04 PM"
  # shortDateFormat Default: "15:04 — Jan 2"
  dateFormat: "January 2, 2006 at 3:04 PM"
  shortDateFormat: "15:04 — Jan 2"
  # This string will be displayed after each time displayed
  # Set it for instance to " UTC" to indicate UTC times
  # or a specific time zone, ie " America/New_York"
  # You can also instead used a translated string per language
  timezoneString: " UTC"

  # Path to logo image from the /static folder.
  logo: "https://androidwedakarayo.com/content/images/2020/09/Asset-1.png"

  # favicon
  icon: "https://androidwedakarayo.com/favicon.png"
  iconType: "image/png"

  # Descriptions
  meta_description: "This status page provides updated information about our systems normal operation, incidents that may happen and their resolution."
  description_footer: "<a class='text-grey-darkest' title='Visit androidwedakarayo.com' href='https://androidwedakarayo.com/'>androidwedakarayo.com</a> provides Tech news."
  description_header: "Information about <a class='text-grey-darkest' title='Visit androidwedakarayo.com' href='https://androidwedakarayo.com/'>Android වැඩකාරයෝ</a> systems operations.<br />Follow us <a class='text-grey-darkest' title='Visit our page on Twitter' href='https://www.twitter.com/androidwdlka'>on Twitter</a> to be alerted of new events."

  copyrightHolder: "Android වැඩකාරයෝ."

  # Disqus commenting per issue: set your Disqus shortname here
  # Leave empty for no discussion at all.
  # You can also enable/disable discussions per issue
  disqusShortname:

  # Layout
  eventsPerPage: 10

############################################################
## More default config. in /config/_default/params.yml
############################################################
